Feature/hu01 list albumes
MISO-4203-E07/vinilos-movil pull request #31
Opened 2021-11-01 17:26 UTC by Yesidtombe

- Template album created
- Recyclerview with adapter implemented
- Loaded with static data

2021-11-02 15:17 UTC, andalm requested changes

2021-11-02 15:17 UTC, andalm commented on .idea/$CACHE_FILE$
> +<?xml version="1.0" encoding="UTF-8"?>
@Yesidtombe esto se deja?

2021-11-02 15:17 UTC, andalm commented on .idea/compiler.xml
> +<?xml version="1.0" encoding="UTF-8"?>
@Yesidtombe Esto tambi'en?

2021-11-02 22:41 UTC, jandresboyaca commented on .idea/compiler.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Ya fue removido en develop, solo tiene que hacer pull

2021-11-03 02:22 UTC, Yesidtombe commented on .idea/$CACHE_FILE$
> +<?xml version="1.0" encoding="UTF-8"?>
Fixed

2021-11-03 02:22 UTC, andalm approved these changes

2021-11-03 02:23 UTC, Yesidtombe commented on .idea/compiler.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Listo

2021-11-03 02:24 UTC, juandial01 approved these changes

2021-11-03 02:24 UTC, merged