Add nav bar
MISO-4203-E07/vinilos-movil pull request #35
Opened 2021-11-12 00:08 UTC by jandresboyaca

List Artists

2021-11-14 07:06 UTC, juandial01 approved these changes
Yo la veo bien

2021-11-14 19:28 UTC, andalm approved these changes

2021-11-14 22:52 UTC, Yesidtombe requested changes
Muy buen trabajo, se paso de activities a fragments y todo funciona. Solo están los comentarios para mejorar un poco el código. De resto está excelente

La imagen que está en app/src/main/ic_one-playstore.png no sé para que es.

2021-11-14 22:52 UTC, Yesidtombe commented on app/src/main/java/co/edu/uniandes/vinilos/view/album/AlbumAdapter.kt
> +    var onArtistSelected: ((id: Int) -> Unit)? = null
La variable que almacena la lamda debería llamarse como venía antes "onAlbumSelected", ya que estamos en AlbumAdapter y le damos click a un album. El adaptador del Artist se llama igual pero está bien

2021-11-14 22:52 UTC, Yesidtombe commented on app/src/main/java/co/edu/uniandes/vinilos/view/album/AlbumAdapter.kt
> -        onAlbumSelected?.invoke(data[position].id)
Si se cambia la variable aquí también

2021-11-14 22:52 UTC, Yesidtombe commented on app/src/main/java/co/edu/uniandes/vinilos/view/album/AlbumFragment.kt
> +        adapter.onArtistSelected = this::goToDetailAlbum
Debería ir adapter.onAlbumSelected y hace referencia a la funcion goToDetailAlbum

2021-11-14 22:52 UTC, Yesidtombe commented on app/src/main/java/co/edu/uniandes/vinilos/viewmodel/ArtistViewModel.kt
> +    val album = MutableLiveData<Performer>()
La variable hace referencia a un Performer, debería llamarse así mismo

2021-11-14 22:52 UTC, Yesidtombe commented on app/src/main/java/co/edu/uniandes/vinilos/viewmodel/ArtistViewModel.kt
> +            album.postValue(it)
Se hace refactor a la variable, cambia aquí también

2021-11-14 22:52 UTC, Yesidtombe commented on app/src/main/res/layout/fragment_album.xml
> +    <TextView
Este textView parece que no contiene información, se podría remover

2021-11-14 22:52 UTC, Yesidtombe commented on app/src/main/res/layout/fragment_artist.xml
> +    <TextView
Este textView parece que no contiene información, se podría remover

2021-11-14 22:52 UTC, Yesidtombe commented on app/src/main/res/layout/template_item_album.xml
> +            android:id="@+id/ivArtist"
Tiene el mismo id que el template del artist, no se debió cambiar. Debería ser ivAlbum ya que es el layout del album

2021-11-14 22:52 UTC, Yesidtombe commented on app/src/main/res/layout/template_item_album.xml
> +            android:id="@+id/tvNameArtist"
Tiene el mismo id que el template del artist, no se debió cambiar. Debería ser tvNameAlbum ya que es el layout del album

2021-11-14 22:52 UTC, Yesidtombe commented on app/src/main/res/layout/template_item_album.xml
> +            app:layout_constraintEnd_toEndOf="@+id/ivArtist"
Refactorizando el id del textView e ImageView cambian estas referencias

2021-11-15 00:53 UTC, Yesidtombe approved these changes
Perfecto, gracias

2021-11-15 00:56 UTC, merged